const fs = require('fs');

// ============================================================
// HAND-CURATED IMAGE + RESTAURANT DATABASE
// Every entry: { img: place_image, foodImg: food_image, restaurants: [...], foods: [...] }
// ============================================================

const placeDB = {
  // ========== DELHI ==========
  "Red Fort (Lal Qila)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Red_Fort_in_Delhi_03-2016_img3.jpg/800px-Red_Fort_in_Delhi_03-2016_img3.jpg", restaurants: ["Karim's", "Al Jawahar", "Moti Mahal"], foods: ["Butter Chicken","Nihari","Biryani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Qutub Minar": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Qutub_Minar_mbread.jpg/800px-Qutub_Minar_mread.jpg", restaurants: ["Olive Bar & Kitchen", "Qutub Institutional Area Cafes"], foods: ["Seekh Kebab", "Rumali Roti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Seekh_kebab.JPG/800px-Seekh_kebab.JPG" },
  "Humayun's Tomb": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Humayun%27s_Tomb%2C_Delhi.jpg/800px-Humayun%27s_Tomb%2C_Delhi.jpg", restaurants: ["Khan Chacha", "Nizamuddin Kebab Shops"], foods: ["Kebab","Parantha"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chicken_Tikka_%281%29.jpg/800px-Chicken_Tikka_%281%29.jpg" },
  "India Gate": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/India_Gate_in_New_Delhi_03-2016.jpg/800px-India_Gate_in_New_Delhi_03-2016.jpg", restaurants: ["Andhra Pradesh Bhavan Canteen", "Pandara Road Restaurants"], foods: ["Ice Cream Kulfi", "Chaat"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Pani_Puri_or_Gol_Gappa.jpg/800px-Pani_Puri_or_Gol_Gappa.jpg" },
  "Lotus Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/LotusDelhi.jpg/800px-LotusDelhi.jpg", restaurants: ["Evergreen Sweet Corner Nehru Place", "Bikanervala"], foods: ["Chole Bhature","Samosa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },
  "Swaminarayan Akshardham": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Akshardham_Delhi.jpg/800px-Akshardham_Delhi.jpg", restaurants: ["Premvati Food Court (Inside)"], foods: ["Gujarati Thali","Rajasthani Thali"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Chandni Chowk": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Chandni_Chowk_Market.jpg/800px-Chandni_Chowk_Market.jpg", restaurants: ["Paranthe Wali Gali", "Natraj Dahi Bhalle", "Old Famous Jalebi Wala"], foods: ["Parantha", "Jalebi", "Dahi Bhalle"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Jalebi_on_sale.jpg/800px-Jalebi_on_sale.jpg" },
  "Lodhi Garden": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Lodhi_Garden_-_Bara_Gumbad_and_Mosque.jpg/800px-Lodhi_Garden_-_Bara_Gumbad_and_Mosque.jpg", restaurants: ["Lodi The Garden Restaurant", "Indian Accent"], foods: ["Continental", "Indian Fusion"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Jama Masjid": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Jama_Masjid_-_In_the_Courtyard.jpg/800px-Jama_Masjid_-_In_the_Courtyard.jpg", restaurants: ["Karim's", "Al Jawahar", "Haji Shabrati Nihari Wale"], foods: ["Nihari", "Seekh Kebab", "Biryani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Dilli Haat": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Dilli_Haat_2.jpg/800px-Dilli_Haat_2.jpg", restaurants: ["State Food Stalls (inside Dilli Haat)"], foods: ["Litti Chokha", "Momos", "Regional cuisine"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Karim's": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Jama_Masjid_-_In_the_Courtyard.jpg/800px-Jama_Masjid_-_In_the_Courtyard.jpg", restaurants: ["Karim's Original (Jama Masjid)"], foods: ["Mutton Burra", "Chicken Jahangiri"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Connaught Place (CP)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Connaught_Place_New_Delhi.jpg/800px-Connaught_Place_New_Delhi.jpg", restaurants: ["Wenger's", "Saravana Bhavan", "Farzi Cafe"], foods: ["Chole Kulche", "Dosa", "Street Food"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },
  "Hauz Khas Village": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Hauz_Khas_Lake_and_Madrasa.jpg/800px-Hauz_Khas_Lake_and_Madrasa.jpg", restaurants: ["Social Hauz Khas", "Naivedyam", "Yeti"], foods: ["Continental", "Tibetan"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Gurudwara Bangla Sahib": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Gurudwara_Bangla_Sahib_New_Delhi.jpg/800px-Gurudwara_Bangla_Sahib_New_Delhi.jpg", restaurants: ["Langar (Free community kitchen inside)"], foods: ["Dal Roti", "Kheer"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Agrasen ki Baoli": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Agrasen_ki_Baoli%2C_Central_Delhi.jpg/800px-Agrasen_ki_Baoli%2C_Central_Delhi.jpg", restaurants: ["Sagar Ratna CP", "Rajdhani Thali"], foods: ["South Indian","Thali"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Nizamuddin Dargah": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Interior_of_the_Nizamuddin_Dargah.jpg/800px-Interior_of_the_Nizamuddin_Dargah.jpg", restaurants: ["Ghalib Kabab Corner", "Karim's Nizamuddin"], foods: ["Kebab", "Biryani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Khan Market": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Khan_Market%2C_New_Delhi.jpg/800px-Khan_Market%2C_New_Delhi.jpg", restaurants: ["Big Chill", "Perch Wine & Coffee Bar", "Town Hall"], foods: ["Italian","Cafe Food"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg" },
  "Paranthe Wali Gali": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Chandni_Chowk_Market.jpg/800px-Chandni_Chowk_Market.jpg", restaurants: ["Pt. Kanhaiyalal Durga Prasad Parantha", "Pt. Gaya Prasad Shiv Charan"], foods: ["Stuffed Parantha", "Rabri"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Aloo_paratha_%28close-up%29.jpg/800px-Aloo_paratha_%28close-up%29.jpg" },
  "Raj Ghat": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Gandhi_Smriti.jpg/800px-Gandhi_Smriti.jpg", restaurants: ["Moti Mahal Delux", "Gujarati Bhavan Canteen"], foods: ["Tandoori Chicken","Dal Makhani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Safdarjung Tomb": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Safdarjungs_Tomb_New_Delhi.jpg/800px-Safdarjungs_Tomb_New_Delhi.jpg", restaurants: ["Gulati Restaurant", "Dhaba by Claridges"], foods: ["Butter Chicken","Naan"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Butter_Chicken%2C_Delhi_Style.jpg/800px-Butter_Chicken%2C_Delhi_Style.jpg" },

  // ========== GOA ==========
  "Basilica of Bom Jesus": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Basilica_of_Bom_Jesus_-_Goa.jpg/800px-Basilica_of_Bom_Jesus_-_Goa.jpg", restaurants: ["Viva Panjim", "Ritz Classic"], foods: ["Fish Curry Rice","Bebinca"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Fort Aguada": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Fort_Aguada_Goa.jpg/800px-Fort_Aguada_Goa.jpg", restaurants: ["Britto's Baga", "Curlies", "Thalassa"], foods: ["Goan Fish Thali","Prawn Balchão"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Dudhsagar Waterfalls": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dudhsagar_Falls.jpg/800px-Dudhsagar_Falls.jpg", restaurants: ["Spice Plantation Lunch", "Local Dhabas"], foods: ["Pork Vindaloo","Xacuti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Chapora Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Chapora_Fort_View.jpg/800px-Chapora_Fort_View.jpg", restaurants: ["Thalassa", "Gunpowder Assagao"], foods: ["Chorizo Pao","Fish Recheado"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Baga Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Baga_Beach_goa.jpg/800px-Baga_Beach_goa.jpg", restaurants: ["Britto's", "Fiesta", "St. Anthony's Bar"], foods: ["Seafood Platter","Goan Sausage"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Calangute Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Calangute_Beach_2.jpg/800px-Calangute_Beach_2.jpg", restaurants: ["Souza Lobo", "Infantaria"], foods: ["Prawn Curry","Poi Bread"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Se Cathedral": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Se_Cathedral%2C_Goa.jpg/800px-Se_Cathedral%2C_Goa.jpg", restaurants: ["Viva Panjim", "Venite Restaurant"], foods: ["Goan Pork Sorpotel","Sannas"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Anjuna Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Anjuna_beach.jpg/800px-Anjuna_beach.jpg", restaurants: ["Curlies Beach Shack", "Artjuna Cafe"], foods: ["Fish Thali","Feni Cocktails"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Palolem Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Palolem_beach.jpg/800px-Palolem_beach.jpg", restaurants: ["Dropadi Restaurant", "Magic Italy"], foods: ["Crab Xec Xec","Bebinca"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Morjim Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Anjuna_beach.jpg/800px-Anjuna_beach.jpg", restaurants: ["Sublime", "Cafe Mojo"], foods: ["Goan Fish Curry","Rava Fried Fish"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Mandovi River Cruise": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Mandovi_River_Panjim.jpg/800px-Mandovi_River_Panjim.jpg", restaurants: ["Fisherman's Wharf", "Black Sheep Bistro"], foods: ["Prawn Balchão","Goan Sausage Pulao"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Spice Plantation Tour": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dudhsagar_Falls.jpg/800px-Dudhsagar_Falls.jpg", restaurants: ["Plantation Buffet Lunch"], foods: ["Spice-infused Goan Curry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Old Goa Heritage Walk": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Basilica_of_Bom_Jesus_-_Goa.jpg/800px-Basilica_of_Bom_Jesus_-_Goa.jpg", restaurants: ["Cafe Real PANJIM", "Kokni Kanteen"], foods: ["Pork Vindaloo","Bibinca"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Fontainhas (Latin Quarter)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Fontainhas.jpg/800px-Fontainhas.jpg", restaurants: ["Viva Panjim", "Cafe Bodega"], foods: ["Bebinca","Dodol"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Vagator Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Chapora_Fort_View.jpg/800px-Chapora_Fort_View.jpg", restaurants: ["Thalassa", "Antares Restaurant"], foods: ["Seafood Platter"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },

  // ========== GUJARAT ==========
  "Ahmedabad": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Sabarmati_Ashram_02.jpg/800px-Sabarmati_Ashram_02.jpg", restaurants: ["Manek Chowk Food Stalls", "Agashiye", "Vishalla"], foods: ["Dhokla","Fafda","Thepla","Handvo"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Dhokla_on_a_plate.jpg/800px-Dhokla_on_a_plate.jpg" },
  "Statue of Unity": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Statue_of_Unity.jpg/800px-Statue_of_Unity.jpg", restaurants: ["Ekta Nagar Food Court", "Shrestha Veg Restaurant"], foods: ["Gujarati Thali","Dal Dhokli"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Gir National Park": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Gir_lion.jpg/800px-Gir_lion.jpg", restaurants: ["Gir Jungle Lodge Restaurant", "Lion Safari Camp"], foods: ["Bajra Roti","Khichdi","Chaas"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Dwarka": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dwarkadhish_Temple.jpg/800px-Dwarkadhish_Temple.jpg", restaurants: ["Toral Dining Hall", "Shrinathji Restaurant"], foods: ["Khichdi","Thepla"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Somnath": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Somnath_mandir.jpg/800px-Somnath_mandir.jpg", restaurants: ["Somnath Guest House Canteen", "Jay Somnath Restaurant"], foods: ["Gujarati Thali","Dal Chawal"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Rann of Kutch": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Rann_of_Kutch%2C_Gujarat%2C_India.jpg/800px-Rann_of_Kutch%2C_Gujarat%2C_India.jpg", restaurants: ["Tent City Dining", "Rann Utsav Pavilion"], foods: ["Kutchi Dabeli","Bajra Roti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Rajkot": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Clock_tower_rajkot.jpg/800px-Clock_tower_rajkot.jpg", restaurants: ["Temptations Restaurant", "Kathiyawadi Restaurants"], foods: ["Sev Tameta","Bhajiya"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Surat": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Surat_Dutch_Gardens.jpg/800px-Surat_Dutch_Gardens.jpg", restaurants: ["Surat Famous Locho Stalls", "Bombay Kulfi"], foods: ["Locho","Ghari"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Bhavnagar": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Somnath_mandir.jpg/800px-Somnath_mandir.jpg", restaurants: ["Sankalp Restaurant", "Toral"], foods: ["Gathiya","Fish Curry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },

  // ========== HIMACHAL PRADESH ==========
  "Shimla Ridge & Mall Road": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mall_road_Shimla.jpg/800px-Mall_road_Shimla.jpg", restaurants: ["Cafe Simla Times", "Wake & Bake", "Baljees"], foods: ["Siddu", "Madra", "Tudkiya Bhath"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Kalka-Shimla Toy Train": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/KSR_Train_at_Summer_Hill_railway_station.jpg/800px-KSR_Train_at_Summer_Hill_railway_station.jpg", restaurants: ["Baljees", "Indian Coffee House Shimla"], foods: ["Himachali Dham", "Babru"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Manali Old Village": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/View_of_the_Manali_city%2C_Himachal_Pradesh.jpg/800px-View_of_the_Manali_city%2C_Himachal_Pradesh.jpg", restaurants: ["Drifters Cafe", "Lazy Dog Lounge", "Johnson's Cafe"], foods: ["Trout Fish", "Momos", "Thukpa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Solang Valley": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Solang_Valley_in_July_2019.jpg/800px-Solang_Valley_in_July_2019.jpg", restaurants: ["Mountain Top Restaurant", "Chopsticks Manali"], foods: ["Maggi", "Siddu"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Rohtang Pass": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Rohtang_Pass_2011.jpg/800px-Rohtang_Pass_2011.jpg", restaurants: ["Dhaba at Marhi", "Rohtang View Cafe"], foods: ["Rajma Chawal","Hot Maggi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Dharamshala & McLeod Ganj": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/McLeod_Ganj_Dharamsala.jpg/800px-McLeod_Ganj_Dharamsala.jpg", restaurants: ["Illiterati Cafe", "Tibet Kitchen", "Jimmy's Italian Kitchen"], foods: ["Thukpa", "Momos", "Tingmo"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Tsuglagkhang Complex": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/McLeod_Ganj_Dharamsala.jpg/800px-McLeod_Ganj_Dharamsala.jpg", restaurants: ["Tibet Kitchen", "Lung Ta Japanese"], foods: ["Tibetan Bread","Butter Tea"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Bhagsunag Waterfall": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/McLeod_Ganj_Dharamsala.jpg/800px-McLeod_Ganj_Dharamsala.jpg", restaurants: ["Shiva Cafe Bhagsunag"], foods: ["Pancakes","Israeli Food"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Bir Billing": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Paragliding_Bir_Billing.jpg/800px-Paragliding_Bir_Billing.jpg", restaurants: ["Vairagi Cafe", "Garden Cafe Bir"], foods: ["Momos","Tibetan Cuisine"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Kasauli": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mall_road_Shimla.jpg/800px-Mall_road_Shimla.jpg", restaurants: ["Hangout Rooftop Bar", "Narinder Sweets"], foods: ["Himachali Thali"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Kufri": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mall_road_Shimla.jpg/800px-Mall_road_Shimla.jpg", restaurants: ["Kufri Fun World Restaurant"], foods: ["Pakora","Hot Chai"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Spiti Valley": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Spiti_Valley_2020.jpg/800px-Spiti_Valley_2020.jpg", restaurants: ["Sol Cafe Kaza", "The Himalayan Cafe"], foods: ["Thukpa","Chhang"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Key Monastery": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Spiti_Valley_2020.jpg/800px-Spiti_Valley_2020.jpg", restaurants: ["Key Monastery Canteen"], foods: ["Butter Tea","Tsampa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Chandratal Lake": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Spiti_Valley_2020.jpg/800px-Spiti_Valley_2020.jpg", restaurants: ["Camp Side Dining"], foods: ["Rajma Rice","Maggi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Khajjiar (Mini Switzerland)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Khajjiar.jpg/800px-Khajjiar.jpg", restaurants: ["Hotel Devdar Restaurant"], foods: ["Madra","Channa Madra"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },
  "Dalai Lama Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/McLeod_Ganj_Dharamsala.jpg/800px-McLeod_Ganj_Dharamsala.jpg", restaurants: ["Tibet Kitchen"], foods: ["Momos","Butter Tea"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Prashar Lake": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/View_of_the_Manali_city%2C_Himachal_Pradesh.jpg/800px-View_of_the_Manali_city%2C_Himachal_Pradesh.jpg", restaurants: ["Trek-side Dhabas"], foods: ["Siddu","Dal"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/800px-Good_Food_Display_-_NCI_Visuals_Online.jpg" },

  // ========== KERALA ==========
  "Munnar Tea Gardens": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Munnar_hillstation_kerala.jpg/800px-Munnar_hillstation_kerala.jpg", restaurants: ["Saravana Bhavan Munnar", "Rapsy Restaurant"], foods: ["Appam & Stew","Puttu & Kadala"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Puttu-Kadala.jpg/800px-Puttu-Kadala.jpg" },
  "Alleppey Backwaters": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/A_houseboat_in_Alleppey%2C_Kerala.jpg/800px-A_houseboat_in_Alleppey%2C_Kerala.jpg", restaurants: ["Houseboat Kitchen", "Dreamers Cafe"], foods: ["Karimeen Pollichathu","Kerala Fish Curry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Varkala Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Varkala_beach%2C_Kerala%2C_India.jpg/800px-Varkala_beach%2C_Kerala%2C_India.jpg", restaurants: ["Cafe del Mar Varkala", "Abba Restaurant"], foods: ["Prawn Moilee","Fish Fry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Kovalam Beach": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Kovalam_Beach_Kerala.jpg/800px-Kovalam_Beach_Kerala.jpg", restaurants: ["Fusion Restaurant", "Bait Restaurant"], foods: ["Malabar Parotta","Kerala Prawn Curry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Wayanad Wildlife Sanctuary": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Wayanad_Greenery.jpg/800px-Wayanad_Greenery.jpg", restaurants: ["Edakkal Hermitage Restaurant", "Vythiri Resort Dining"], foods: ["Dosa Ghee Roast","Bamboo Chicken"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Puttu-Kadala.jpg/800px-Puttu-Kadala.jpg" },
  "Athirappilly Waterfalls": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Athirappilly_Falls.jpg/800px-Athirappilly_Falls.jpg", restaurants: ["Rainforest Resort Restaurant"], foods: ["Kerala Sadya","Tapioca & Fish Curry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Periyar National Park": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Periyar_lake.jpg/800px-Periyar_lake.jpg", restaurants: ["Spice Village Restaurant Thekkady", "Periyar House Canteen"], foods: ["Banana Chips","Kerala Meals"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Puttu-Kadala.jpg/800px-Puttu-Kadala.jpg" },
  "Fort Kochi": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Chinese_Fishing_nets_Fort_Kochi.jpg/800px-Chinese_Fishing_nets_Fort_Kochi.jpg", restaurants: ["Kashi Art Cafe", "Fort House Restaurant", "Oceanos"], foods: ["Malabar Biryani","Appam & Stew"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Kumarakom Backwaters": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/A_houseboat_in_Alleppey%2C_Kerala.jpg/800px-A_houseboat_in_Alleppey%2C_Kerala.jpg", restaurants: ["Kumarakom Resort Restaurant"], foods: ["Karimeen Fry","Duck Roast"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Bekal Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Bekal_Fort_kasaragod.jpg/800px-Bekal_Fort_kasaragod.jpg", restaurants: ["Bekal Ripples Resort"], foods: ["Malabar Dum Biryani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Padmanabhaswamy Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Padmanabhaswamy_Temple_Thiruvananthapuram.jpg/800px-Padmanabhaswamy_Temple_Thiruvananthapuram.jpg", restaurants: ["Ariya Nivaas", "Villa Maya"], foods: ["Sadya","Payasam"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Puttu-Kadala.jpg/800px-Puttu-Kadala.jpg" },

  // ========== LADAKH ==========
  "Pangong Tso": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pangong_Tso.jpg/800px-Pangong_Tso.jpg", restaurants: ["Lakeside Tent Camps"], foods: ["Thukpa","Momos","Butter Tea"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Nubra Valley": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Sand_Dunes_of_Nubra_Valley.jpg/800px-Sand_Dunes_of_Nubra_Valley.jpg", restaurants: ["Hundar Guest House", "Nubra Ecolodge"], foods: ["Skyu","Tsampa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Thiksey Monastery": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Thikse_Monastery.jpg/800px-Thikse_Monastery.jpg", restaurants: ["Thiksey Kitchen", "Alchi Kitchen"], foods: ["Butter Tea","Skyu"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Turtuk Village": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Sand_Dunes_of_Nubra_Valley.jpg/800px-Sand_Dunes_of_Nubra_Valley.jpg", restaurants: ["Balti Heritage Kitchen"], foods: ["Balti Cuisine","Apricot Cake"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Magnetic Hill": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Magnetic_Hill_Leh.jpg/800px-Magnetic_Hill_Leh.jpg", restaurants: ["Magnetic Hill Dhaba"], foods: ["Maggi","Chai","Momos"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Hanle": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pangong_Tso.jpg/800px-Pangong_Tso.jpg", restaurants: ["Hanle Monastery Guest House"], foods: ["Thukpa","Skyu"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Zanskar Valley (Padum)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pangong_Tso.jpg/800px-Pangong_Tso.jpg", restaurants: ["Padum Guest House Kitchen"], foods: ["Thukpa","Butter Tea"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Tso Moriri": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pangong_Tso.jpg/800px-Pangong_Tso.jpg", restaurants: ["Korzok Village Homestays"], foods: ["Tibetan Bread","Chhang"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Leh Palace": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Leh_Palace_2011.jpg/800px-Leh_Palace_2011.jpg", restaurants: ["The Tibetan Kitchen Leh", "Bon Appetit", "Gesmo Restaurant"], foods: ["Momos","Thukpa","Skyu"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Hemis National Park": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Thikse_Monastery.jpg/800px-Thikse_Monastery.jpg", restaurants: ["Hemis Cafe"], foods: ["Momos","Butter Tea"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },

  // ========== MAHARASHTRA ==========
  "Ajanta Caves": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Ajanta_%28panoramic_view%29.jpg/800px-Ajanta_%28panoramic_view%29.jpg", restaurants: ["MTDC Restaurant Ajanta", "Fardapur Dhabas"], foods: ["Hurda","Jowar Bhakri","Zunka"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Ellora Caves": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Kailasha_temple_at_ellora.jpg/800px-Kailasha_temple_at_ellora.jpg", restaurants: ["The Garden Restaurant Ellora", "Hotel Kailas"], foods: ["Naan Qalia","Dalma"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Gateway of India": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/800px-Mumbai_03-2016_30_Gateway_of_India.jpg", restaurants: ["Leopold Cafe", "Bademiya", "Cafe Mondegar"], foods: ["Vada Pav","Pav Bhaji","Bombil Fry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Marine Drive": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Marine_Drive_skyline.jpg/800px-Marine_Drive_skyline.jpg", restaurants: ["Pizza By The Bay", "Cafe Madras"], foods: ["Bhel Puri","Sev Puri","Vada Pav"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Chhatrapati Shivaji Maharaj Terminus (CSMT)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Mumbai_Train_Station.jpg/800px-Mumbai_Train_Station.jpg", restaurants: ["Britannia & Co.", "Jimmy Boy"], foods: ["Bun Maska","Irani Chai"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Haji Ali Dargah": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Haji_Ali_Dargah_2012.jpg/800px-Haji_Ali_Dargah_2012.jpg", restaurants: ["Haji Ali Juice Centre", "Bade Miya"], foods: ["Fresh Fruit Juice","Kebab Roll"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Shirdi Sai Baba Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Sai_baba_samadhi_mandir_.jpg/800px-Sai_baba_samadhi_mandir_.jpg", restaurants: ["Prasadalay Shirdi", "Hotel Saishree"], foods: ["Maharashtrian Thali","Modak"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg" },
  "Dagdusheth Halwai Ganpati": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Dagadusheth_Ganpati.jpg/800px-Dagadusheth_Ganpati.jpg", restaurants: ["Dagdusheth Halwai Sweet Shop", "Bedekar Misal Pune"], foods: ["Misal Pav","Modak","Puran Poli"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Bhimashankar Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Dagadusheth_Ganpati.jpg/800px-Dagadusheth_Ganpati.jpg", restaurants: ["MTDC Restaurant Bhimashankar"], foods: ["Vada Pav","Misal Pav"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Leopold Cafe": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/800px-Mumbai_03-2016_30_Gateway_of_India.jpg", restaurants: ["Leopold Cafe (itself)"], foods: ["Continental","Sizzlers"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },
  "Sardar Pav Bhaji": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg", restaurants: ["Sardar Refreshments"], foods: ["Pav Bhaji"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pav_Bhaji.jpg/800px-Pav_Bhaji.jpg" },

  // ========== PUNJAB ==========
  "Golden Temple (Harmandir Sahib)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Golden_Temple%2C_Amritsar_09.jpg/800px-Golden_Temple%2C_Amritsar_09.jpg", restaurants: ["Langar (Free Kitchen)", "Kesar Da Dhaba", "Bharawan Da Dhaba"], foods: ["Amritsari Kulcha","Lassi","Langar Dal"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Wagah Border": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Wagah_Border_Ceremony.jpg/800px-Wagah_Border_Ceremony.jpg", restaurants: ["Pehalwan Dhaba", "Sukhdev Dhaba Murthal"], foods: ["Amritsari Naan","Chole"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },
  "Jallianwala Bagh": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Jallianwala_Bagh%2C_Amritsar.jpg/800px-Jallianwala_Bagh%2C_Amritsar.jpg", restaurants: ["Kesar Da Dhaba","Brothers Dhaba"], foods: ["Amritsari Fish","Makki Di Roti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Rock Garden": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Rock_Garden_of_Chandigarh.jpg/800px-Rock_Garden_of_Chandigarh.jpg", restaurants: ["Pal Dhaba Chandigarh", "Mehfil Restaurant"], foods: ["Chole Bhature","Butter Chicken"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },
  "Virasat-e-Khalsa": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Virasat-e-Khalsa_Panorama.jpg/800px-Virasat-e-Khalsa_Panorama.jpg", restaurants: ["Anandpur Sahib Langars"], foods: ["Langar Prasad","Kada Prasad"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Gobindgarh Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Golden_Temple%2C_Amritsar_09.jpg/800px-Golden_Temple%2C_Amritsar_09.jpg", restaurants: ["Sarhad Restaurant (inside fort)"], foods: ["Amritsari Kulcha","Sarson Da Saag"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Kesar Da Dhaba": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Golden_Temple%2C_Amritsar_09.jpg/800px-Golden_Temple%2C_Amritsar_09.jpg", restaurants: ["Kesar Da Dhaba (itself)"], foods: ["Dal Makhani","Amritsari Kulcha"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Dal_makhani.jpg/800px-Dal_makhani.jpg" },
  "Sukhna Lake": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sukhna_Lake%2C_Chandigarh.JPG/800px-Sukhna_Lake%2C_Chandigarh.JPG", restaurants: ["Lake View Cafe", "Pal Dhaba"], foods: ["Chole Bhature","Amritsari Kulcha"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },
  "The Capitol Complex": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Rock_Garden_of_Chandigarh.jpg/800px-Rock_Garden_of_Chandigarh.jpg", restaurants: ["Indian Coffee House Sector 17"], foods: ["South Indian Coffee","Samosa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chole_bhature.jpg/800px-Chole_bhature.jpg" },

  // ========== RAJASTHAN ==========
  "Amber Palace (Amer Fort)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Amer_Fort%2C_Jaipur.jpg/800px-Amer_Fort%2C_Jaipur.jpg", restaurants: ["1135 AD at Amer", "Chokhi Dhani"], foods: ["Dal Baati Churma","Laal Maas","Ghevar"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "City Palace": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/City_Palace_Jaipur.jpg/800px-City_Palace_Jaipur.jpg", restaurants: ["Suvarna Mahal", "Niros"], foods: ["Pyaaz Kachori","Rabri"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Mehrangarh Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/MehrangarhFort.jpg/800px-MehrangarhFort.jpg", restaurants: ["Chokelao Mahal Restaurant", "Jhankar Choti Haveli"], foods: ["Mirchi Vada","Mawa Kachori"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Jaisalmer Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Jaisalmer_fort34.jpg/800px-Jaisalmer_fort34.jpg", restaurants: ["The Trio Restaurant", "Free Tibet", "Saffron Restaurant"], foods: ["Ker Sangri","Gatte Ki Sabzi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Hawa Mahal": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Hawa_Mahal_2011.jpg/800px-Hawa_Mahal_2011.jpg", restaurants: ["Wind View Cafe", "Rawat Mishthan Bhandar"], foods: ["Pyaaz Kachori","Kulfi Faluda"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Pushkar Lake & Brahma Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pushkar_Lake1.jpg/800px-Pushkar_Lake1.jpg", restaurants: ["Om Shiva Garden", "Sunset Cafe Pushkar"], foods: ["Malpua","Dal Baati"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Ranthambore National Park": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ranthambore_Fort_04.jpg/800px-Ranthambore_Fort_04.jpg", restaurants: ["Ranthambore Resort Dining"], foods: ["Laal Maas","Jungle Maas"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Chittorgarh Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Vijay_Stambha_Chittorgarh.jpg/800px-Vijay_Stambha_Chittorgarh.jpg", restaurants: ["Mewar Haveli Restaurant"], foods: ["Mawa Kachori","Gharonda"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Kumbhalgarh Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Kumbhalgarh_Fort.jpg/800px-Kumbhalgarh_Fort.jpg", restaurants: ["Aodhi Restaurant"], foods: ["Dal Baati","Gatte Ki Sabzi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Lake Pichola": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Lake_Pichola%2C_Udaipur.jpg/800px-Lake_Pichola%2C_Udaipur.jpg", restaurants: ["Ambrai Restaurant", "Upre by 1559 AD"], foods: ["Dahi Vada","Gatte Ki Sabzi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Sam Sand Dunes": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sam_sand_dunes.jpg/800px-Sam_sand_dunes.jpg", restaurants: ["Desert Camp Dining"], foods: ["Ker Sangri","Bajra Roti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Nahargarh Fort": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Nahargarh_Fort_Jaipur_Inde_01.jpg/800px-Nahargarh_Fort_Jaipur_Inde_01.jpg", restaurants: ["Padao Restaurant Nahargarh"], foods: ["Pyaaz Kachori","Thali"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Chokhi Dhani": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Amer_Fort%2C_Jaipur.jpg/800px-Amer_Fort%2C_Jaipur.jpg", restaurants: ["Chokhi Dhani Village Resort"], foods: ["Rajasthani Thali","Ghevar"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },
  "Ambrai Restaurant": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Lake_Pichola%2C_Udaipur.jpg/800px-Lake_Pichola%2C_Udaipur.jpg", restaurants: ["Ambrai (itself)"], foods: ["Laal Maas","Dal Baati"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dal_bati.jpg/800px-Dal_bati.jpg" },

  // ========== WEST BENGAL ==========
  "Victoria Memorial": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Victoria_Memorial_Kolkata_panorama.jpg/800px-Victoria_Memorial_Kolkata_panorama.jpg", restaurants: ["Flurys", "Peter Cat", "6 Ballygunge Place"], foods: ["Rasgulla","Mishti Doi","Kosha Mangsho"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Dakshineswar Kali Temple": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Dakshineswar_temple_with_Hooghly.jpg/800px-Dakshineswar_temple_with_Hooghly.jpg", restaurants: ["Annapurna Restaurant", "Bhojohori Manna"], foods: ["Luchi Alur Dom","Cholar Dal"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Howrah Bridge": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Howrah_Bridge%2C_Kolkata.jpg/800px-Howrah_Bridge%2C_Kolkata.jpg", restaurants: ["Tiretti Bazaar Chinese Stalls", "Nizam's"], foods: ["Kathi Roll","Phuchka","Jhal Muri"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Darjeeling Mall Road": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Darjeeling_view_with_Kanchenjunga.jpg/800px-Darjeeling_view_with_Kanchenjunga.jpg", restaurants: ["Glenary's", "Keventer's", "Sonam's Kitchen"], foods: ["Darjeeling Tea","Momos","Thukpa"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Tiger Hill": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Darjeeling_view_with_Kanchenjunga.jpg/800px-Darjeeling_view_with_Kanchenjunga.jpg", restaurants: ["Glenary's Darjeeling","Das Studio Cafe"], foods: ["Tea & Pakoras"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Darjeeling Himalayan Railway (Toy Train)": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Darjeeling_Himalayan_Railway.jpg/800px-Darjeeling_Himalayan_Railway.jpg", restaurants: ["Keventer's", "Tom & Jerry's"], foods: ["Steam Tea","Momo"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Sundarbans National Park": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Sundarban_Tiger.jpg/800px-Sundarban_Tiger.jpg", restaurants: ["Sundarban Houseboat Kitchen"], foods: ["Chingri Malaikari","Bhetki Fish Fry"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/A_fish_curry_from_India.jpg/800px-A_fish_curry_from_India.jpg" },
  "Shantiniketan": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/VisvaBharati_Santiniketan.jpg/800px-VisvaBharati_Santiniketan.jpg", restaurants: ["Ghare Baire Cafe", "Park Guest House"], foods: ["Khichuri","Beguni","Muri Ghonto"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Belur Math": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Belur_Math_Ramakrishna_Temple.jpg/800px-Belur_Math_Ramakrishna_Temple.jpg", restaurants: ["Annapurna Restaurant"], foods: ["Bengali Thali","Mishti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Indian Museum": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Victoria_Memorial_Kolkata_panorama.jpg/800px-Victoria_Memorial_Kolkata_panorama.jpg", restaurants: ["Peter Cat", "Mocambo"], foods: ["Kolkata Biryani","Chelo Kebab"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "St. Paul's Cathedral": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Victoria_Memorial_Kolkata_panorama.jpg/800px-Victoria_Memorial_Kolkata_panorama.jpg", restaurants: ["Flurys Park Street","Arsalan Biryani"], foods: ["Biryani","Mutton Chaap"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
  "Marble Palace": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Victoria_Memorial_Kolkata_panorama.jpg/800px-Victoria_Memorial_Kolkata_panorama.jpg", restaurants: ["Golbari", "Bhojohori Manna"], foods: ["Kosha Mangsho","Luchi"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rasgulla_2.jpg/800px-Rasgulla_2.jpg" },
  "Kalimpong": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Darjeeling_view_with_Kanchenjunga.jpg/800px-Darjeeling_view_with_Kanchenjunga.jpg", restaurants: ["Gompu's Bar & Restaurant"], foods: ["Momos","Sel Roti"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Momos_Nepal.jpg/800px-Momos_Nepal.jpg" },
  "Hazarduari Palace": { img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/VisvaBharati_Santiniketan.jpg/800px-VisvaBharati_Santiniketan.jpg", restaurants: ["Murshidabad Local Eateries"], foods: ["Murshidabad Biryani"], foodImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hyderabadi_biryani.jpg/800px-Hyderabadi_biryani.jpg" },
};

// ============================================
// APPLY TO ALL DATASETS
// ============================================

async function run() {
    const files = fs.readdirSync('dataset').filter(f => f.endsWith('.json') && f !== 'db.json' && f !== 'package.json');

    for (const file of files) {
        console.log('Processing', file);
        let data;
        try {
            data = JSON.parse(fs.readFileSync('dataset/' + file));
        } catch (e) {
            console.error("  Skipping (JSON error):", file);
            continue;
        }

        const items = data.destinations || data.locations || [];
        if (items.length === 0) { console.log("  No items, skipping"); continue; }

        let changed = false;

        for (const dest of items) {
            const entry = placeDB[dest.name];
            if (entry) {
                // Set correct place image
                dest.image_url = entry.img;

                // Set correct food image and data
                if (!dest.food_details) dest.food_details = {};
                dest.food_details.food_image_url = entry.foodImg;
                if (entry.foods && entry.foods.length > 0) {
                    dest.food_details.famous_food = entry.foods;
                }

                // Set restaurants
                if (entry.restaurants && entry.restaurants.length > 0) {
                    dest.restaurants = entry.restaurants;
                }

                changed = true;
            } else {
                // For entries not in our DB, ensure they at least have a valid food_details
                if (!dest.food_details) dest.food_details = { famous_food: [] };
                if (!dest.food_details.food_image_url) {
                    dest.food_details.food_image_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Indian-Thali-Meal.jpg/800px-Indian-Thali-Meal.jpg";
                    changed = true;
                }
                if (!dest.restaurants || dest.restaurants.length === 0) {
                    dest.restaurants = ["Popular local eateries"];
                    changed = true;
                }
                if (!dest.image_url) {
                    dest.image_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Taj_Mahal_in_March_2004.jpg/800px-Taj_Mahal_in_March_2004.jpg";
                    changed = true;
                }
            }
        }

        if (changed) {
            fs.writeFileSync('dataset/' + file, JSON.stringify(data, null, 2));
            console.log('  ✓ Saved', file, '(' + items.length + ' places updated)');
        }
    }

    // Print stats
    console.log('\n=== COVERAGE REPORT ===');
    console.log('Hand-curated entries in database:', Object.keys(placeDB).length);
}

run();
